#!/bin/bash

show_usage()
{
	echo "usage: vm COMMAND COMMAND-PARAMS"
	echo "       vm -h"
}

if [ -z ${EMUFOX_HOME+x} ]
then
	export EMUFOX_HOME="$(dirname "$(realpath "$0")")"
fi

. "$EMUFOX_HOME"/emufox.conf

case "$1" in
	-h)
		case "$2" in
			clean)
				"$_dir_scripts"/vm-clean -h;;
			start)
				"$_dir_scripts"/vm-start -h;;
			stop)
				"$_dir_scripts"/vm-stop -h;;
			status)
				"$_dir_scripts"/vm-status -h;;
			*)
				show_usage
				echo
				echo "Control virtual machines"
				echo
				echo "Invoke \`vm -h' to see this help, otherwise invoke \`vm COMMAND'"
				echo "to execute the subcommand."
				echo
				echo "Available subcommands are:"
				echo
				echo "  clean"
				echo "  start"
				echo "  stop"
				echo "  status"
				;;
		esac
		;;
	clean)
		shift
		"$_dir_scripts"/vm-clean "$@"
		;;
	start)
		shift
		"$_dir_scripts"/vm-start "$@"
		;;
	stop)
		shift
		"$_dir_scripts"/vm-stop "$@"
		;;
	status)
		shift
		"$_dir_scripts"/vm-status "$@"
		;;
	*)
		show_usage >&2
		exit 1
		;;
esac
